/**
 * @nutshell/adapter-sillytavern
 *
 * Exports a SoulBundle to SillyTavern's character card format (V2).
 * Character cards are PNG files with embedded JSON metadata.
 *
 * Spec: https://github.com/malfoyslastname/character-card-spec-v2
 */

import * as fs from "fs/promises";
import * as path from "path";
import type { NutshellAdapter, SoulBundle, ExportResult, ExportOptions } from "@nutshell/core";

const slug = (s: string) =>
  s.toLowerCase().replace(/\s+/g, "-").replace(/[^\w-]/g, "");

interface TavernCardV2 {
  spec: "chara_card_v2";
  spec_version: "2.0";
  data: {
    name: string;
    description: string;
    personality: string;
    scenario: string;
    first_mes: string;
    mes_example: string;
    creator_notes: string;
    system_prompt: string;
    post_history_instructions: string;
    tags: string[];
    creator: string;
    character_version: string;
    extensions: {
      nutshell: {
        world_seed: string;
        tradition: string;
        world_bond: string;
        generated_at: string;
      };
    };
  };
}

export class SillyTavernAdapter implements NutshellAdapter {
  name = "sillytavern";
  description = "Export to SillyTavern character card format (V2 spec)";
  platforms = ["SillyTavern >= 1.10.0"];

  async export(bundle: SoulBundle, outputDir: string, _options?: ExportOptions): Promise<ExportResult> {
    const { soul, world_seed, files, meta } = bundle;
    const name = slug(soul.character_name);
    const dir = outputDir.replace("~", process.env.HOME || "~");
    await fs.mkdir(dir, { recursive: true });

    // Build the character card JSON
    const card: TavernCardV2 = {
      spec: "chara_card_v2",
      spec_version: "2.0",
      data: {
        name: soul.character_name,
        description: [
          soul.essence,
          "",
          `## Ideological Root`,
          soul.ideological_root,
        ].join("\n"),
        personality: [soul.voice, "", soul.stance].join("\n"),
        scenario: [
          `World: ${world_seed.tradition_name}`,
          `"${world_seed.tagline}"`,
          "",
          world_seed.seed_essence,
        ].join("\n"),
        first_mes: soul.catchphrases?.[0]
          ? `*${soul.catchphrases[0]}*`
          : `*${soul.character_name} regards you.*`,
        mes_example: (soul.catchphrases || [])
          .slice(0, 3)
          .map((p) => `<START>\n{{user}}: ...\n{{char}}: "${p}"`)
          .join("\n"),
        creator_notes: `Generated by nutshell v${meta.version}\nWorld: ${world_seed.tradition_name}\nWorld Bond: ${soul.world_bond}`,
        system_prompt: files.soul_md,
        post_history_instructions: files.skill_md,
        tags: [
          world_seed.tradition_name,
          "nutshell",
          "soul-alchemy",
          soul.character_name,
        ],
        creator: "nutshell",
        character_version: meta.version,
        extensions: {
          nutshell: {
            world_seed: world_seed.tradition_name,
            tradition: world_seed.tagline,
            world_bond: soul.world_bond,
            generated_at: meta.generated_at,
          },
        },
      },
    };

    // Write JSON (PNG embedding requires additional tooling)
    const jsonPath = path.join(dir, `${name}.json`);
    await fs.writeFile(jsonPath, JSON.stringify(card, null, 2), "utf-8");

    // Write memory as lorebook
    const lorePath = path.join(dir, `${name}-lorebook.json`);
    const lorebook = {
      entries: [
        {
          key: [soul.character_name],
          content: files.memory_md,
          enabled: true,
          insertion_order: 100,
        },
      ],
    };
    await fs.writeFile(lorePath, JSON.stringify(lorebook, null, 2), "utf-8");

    return {
      files: [
        { path: jsonPath, description: "Character card JSON (V2 spec)" },
        { path: lorePath, description: "Memory as lorebook" },
      ],
      install_command: `# In SillyTavern: Characters → Import → select ${name}.json`,
      notes: [
        `Import ${name}.json in SillyTavern's character panel.`,
        `Import ${name}-lorebook.json as a World Info / Lorebook for memory.`,
        `For PNG card: open SillyTavern → edit character → export as PNG.`,
      ].join("\n"),
    };
  }
}

export default new SillyTavernAdapter();
